steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/mlproject", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/mlproject"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "mlproject",
        "--image",
        "gcr.io/$PROJECT_ID/mlproject",
        "--platform",
        "managed",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--min-instances",
        "0",
        "--max-instances",
        "1",
      ]

images:
  - gcr.io/$PROJECT_ID/mlproject

options:
  logging: CLOUD_LOGGING_ONLY
